services:
  kube-server:
    container_name: kube-server
    hostname: kube-server
    image: rancher/k3s:latest
    command: server --node-taint node-role.kubernetes.io/control-plane:NoSchedule
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      - K3S_TOKEN=${K3S_TOKEN:?err}
      - K3S_KUBECONFIG_OUTPUT=/output/kube.yaml
      - K3S_KUBECONFIG_MODE=644
    volumes:
      - ./data/kube/kubeconfig:/output
      - ./data/kube/node/server:/etc/rancher/node
      - ./data/kube/server:/var/lib/rancher/k3s
      - ./kube/k3s:/etc/rancher/k3s:ro
      - ./kube/manifests:/var/lib/rancher/k3s/server/manifests/dojo:ro
      - ./kube/bin:/usr/local/bin:ro
    ports:
      - 6443:6443  # Kubernetes API Server
      # - 80:80      # Ingress controller port 80
      # - 443:443    # Ingress controller port 443
    extra_hosts:
      - homes-nfs:10.43.0.20

  kube-agent:
    container_name: kube-agent
    hostname: kube-agent
    image: rancher/k3s:latest
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      - K3S_URL=https://kube-server:6443
      - K3S_TOKEN=${K3S_TOKEN:?err}
    volumes:
      - ./data/kube/node/agent:/etc/rancher/node
      - ./data/kube/agent:/var/lib/rancher/k3s
      - ./data/homes:/var/homes:shared
      - ./kube/k3s:/etc/rancher/k3s:ro
      - ./kube/bin:/usr/local/bin:ro
    extra_hosts:
      - homes-nfs:10.43.0.20

  registry:
    container_name: registry
    image: registry:2
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./data/registry:/var/lib/registry

  challenge:
    build:
      context: ./challenge
      target: challenge-final
      args:
        - DEFAULT_INSTALL_SELECTION=${DEFAULT_INSTALL_SELECTION}
        - INSTALL_AFL=${INSTALL_AFL:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_ANGR_MANAGEMENT=${INSTALL_ANGR_MANAGEMENT:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_BUSYBOX=${INSTALL_BUSYBOX:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_CAPSTONE=${INSTALL_CAPSTONE:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_DESKTOP=${INSTALL_DESKTOP:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_GDB=${INSTALL_GDB:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_GECKODRIVER=${INSTALL_GECKODRIVER:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_GHIDRA=${INSTALL_GHIDRA:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_GLOW=${INSTALL_GLOW:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_IDA_FREE=${INSTALL_IDA_FREE:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_BINJA_FREE=${INSTALL_BINJA_FREE:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_KERNEL=${INSTALL_KERNEL:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_RADARE2=${INSTALL_RADARE2:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_RAPPEL=${INSTALL_RAPPEL:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_RP=${INSTALL_RP:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_TCPDUMP=${INSTALL_TCPDUMP:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_TOOLS_APT=${INSTALL_TOOLS_APT:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_TOOLS_PIP=${INSTALL_TOOLS_PIP:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_VIRTIOFSD=${INSTALL_VIRTIOFSD:-${DEFAULT_INSTALL_SELECTION}}
        - INSTALL_WINDOWS=${INSTALL_WINDOWS:-${DEFAULT_INSTALL_SELECTION}}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
        - DOJO_CHALLENGE=${DOJO_CHALLENGE}
      privileged: true
    image: localhost:5000/challenge
    platform: linux/amd64
    entrypoint: /bin/true

  volume_nfs:
    build: ./volume_nfs
    image: localhost:5000/volume-nfs

  ctfd:
    container_name: ctfd
    hostname: ctfd
    build: /opt/CTFd
    platform: linux/amd64
    user: root
    restart: always
    privileged: true
    entrypoint: ""
    command:
      - /bin/sh
      - -c
      - |
        if [ "$DOJO_ENV" != "development" ]; then
          ./docker-entrypoint.sh;
        else
          FLASK_ENV=development WERKZEUG_DEBUG_PIN=off flask run --host 0.0.0.0 --port 8000;
        fi
    ulimits:
        nofile:
            soft: 32768
            hard: 1048576
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://${DB_USER}:${DB_PASS}@${DB_HOST}/${DB_NAME}
      - REDIS_URL=redis://cache:6379
      - WORKERS=8
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
      - SERVER_SENT_EVENTS=false
      - SECRET_KEY=${SECRET_KEY}
      - DOJO_HOST=${DOJO_HOST}
      - HOST_DATA_PATH=/opt/pwn.college/data
      - KUBECONFIG=/var/kubeconfig/kube.yaml
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - INTERNET_FOR_ALL=${INTERNET_FOR_ALL}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    volumes:
      - ./data:/var/data
      - ./data/CTFd/logs:/var/log/CTFd
      - ./data/CTFd/uploads:/var/uploads
      - ./data/homes:/var/homes:shared
      - ./data/challenges:/var/challenges:ro
      - ./data/dojos:/var/dojos
      - ./data/kube/kubeconfig:/var/kubeconfig:ro
      - ./data/ssh_host_keys/ssh_known_hosts:/etc/ssh/ssh_known_hosts:ro
      - ./index.html:/var/index.html:ro
      - ./user_firewall.allowed:/var/user_firewall.allowed:ro
      - /etc/docker/seccomp.json:/etc/docker/seccomp.json:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/pwn.college/dojo_plugin:/opt/CTFd/CTFd/plugins/dojo_plugin:ro
      - /opt/pwn.college/dojo_theme:/opt/CTFd/CTFd/themes/dojo_theme:ro
    healthcheck:
      test:
        - "CMD"
        - "python"
        - "-c"
        - |
          import requests
          response = requests.get('http://localhost:8000')
          response.raise_for_status()
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
        restart: true
      cache:
        condition: service_started

  db:
    container_name: db
    build:
      context: ./db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - DB_EXTERNAL=${DB_EXTERNAL}
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: [/start.sh]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASS}", "-u${DB_USER}", "-h${DB_HOST}"]
      interval: 10s
      timeout: 10s
      retries: 3

  cache:
    container_name: cache
    image: redis:4
    restart: always
    volumes:
      - ./data/redis:/data

  sshd:
    container_name: sshd
    build:
      context: ./sshd
    volumes:
      - ./data/ssh_host_keys:/etc/ssh:ro
      - ./data/kube/kubeconfig:/var/kubeconfig:ro
    environment:
      - KUBECONFIG=/var/kubeconfig/kube.yaml
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - "22:22"

  discord-bot:
    container_name: discord_bot
    build: discord_bot
    restart: on-failure
    environment:
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}

  nginx:
    container_name: nginx
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOCKER_HOST=unix:///tmp/${DOCKER_PSLR}/docker.sock
      - DEFAULT_HOST=${DOJO_HOST}
      - LOG_JSON=true
    volumes:
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - ./nginx-proxy/etc/nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/etc/passwd:/etc/passwd:ro
      - ./data/homes:/var/homes:shared
      - /var/run/docker.sock:/tmp/${DOCKER_PSLR}/docker.sock:ro

  nginx-certs:
    container_name: nginx_certs
    image: nginxproxy/acme-companion
    restart: always
    volumes_from:
      - nginx
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  conf:
  html:
  dhparam:
  certs:
  acme:
