name: Test building and running dojo
on: push
jobs:
  smoketest:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v3

      - name: Info gathering
        run: |
          ls -la /tmp
          df -h

      - name: Install test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          python -m pip install --upgrade pip
          pip install pytest pytest-dependency requests

      - name: Build container
        run:
          docker build -t dojo-test .

      - name: Run Container
        run: |
          docker run \
            --privileged \
            -d \
            -v $(mktemp -d /tmp/dojo-data-XXXXXX):/opt/pwn.college/data:shared \
            -p 2222:22 -p 80:80 -p 443:443 \
            --name dojo-test \
            dojo-test

      - name: Wait for services to be started
        run: |
          docker exec dojo-test dojo wait

      - name: Wait for services to be running
        run: |
          docker exec dojo-test dojo compose logs -f &
          log_pid=$!

          start_time=$(date +%s)
          timeout=120

          until [[ "$(docker exec dojo-test docker inspect --format='{{.State.Health.Status}}' ctfd)" == "healthy" ]]; do
            current_time=$(date +%s)
            elapsed_time=$((current_time - start_time))

            if [[ "$elapsed_time" -ge "$timeout" ]]; then
              kill $log_pid
              echo "Timeout after waiting for $timeout seconds!"
              exit 1
            fi

            sleep 1
          done

          kill $log_pid
          exit 0

      - name: Run tests against container
        run: |
          pytest -vrpP ./test || (docker exec dojo-test docker compose logs && false)



