name: Test building and runnint dojo
on: push
jobs:
  smoketest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Build Container
        run: "docker build -t pwncollege/dojo ."
      - name: Run Container
        run: "docker run --privileged -d -v $PWD:/opt/pwn.college:shared -p 2222:22 -p 80:80 -p 443:443 --name dojo pwncollege/dojo"
      - name: Wait for container to be ready
        run: |
          until docker exec dojo dojo is-setup-finished
          do
            sleep 5
            docker exec dojo journalctl -u pwn.college  | tail -n 5
          done
      - name: Run tests against container
        run: "pytest ./test"
        
      
